"""Created db

Revision ID: 8178f361488d
Revises: 
Create Date: 2022-12-02 15:10:24.562549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8178f361488d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', mysql.INTEGER(display_width=20), nullable=False),
    sa.Column('name_folder', sa.String(length=255), nullable=True),
    sa.Column('id_drive_folder', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', mysql.INTEGER(display_width=20), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=20), nullable=False),
    sa.Column('media_group_id', mysql.INTEGER(), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('folder_id', mysql.INTEGER(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('userinfo')
    op.drop_table('folder')
    # ### end Alembic commands ###
